const tasksJson = [
  {
    platform: "YouTube",
    iconClass: "fa-brands fa-youtube",
    taskDescription: "Follow the YouTube channel",
    reward: "500",
    taskType: "joinCommunity",
    taskLink: "https://www.youtube.com",
    verification: "pending",
    category: "AIRDROP TASKS",
  },
  {
    platform: "TikTok",
    iconClass: "fa-brands fa-tiktok",
    taskDescription: "Follow the TikTok channel",
    reward: "500",
    taskType: "joinCommunity",
    taskLink: "https://www.tiktok.com",
    verification: "completed",
    category: "DAILY TASKS",
  },
  {
    platform: "Telegram",
    iconClass: "fa-brands fa-telegram",
    taskDescription: "Follow the TG channel",
    reward: "500",
    groupChatId: "testhroup21",
    taskType: "joinTelegramCommunity",
    taskLink: "https://t.me/testhroup21",
    verification: "claimed",
    category: "DAILY TASKS",
  },
  {
    platform: "Twitter",
    iconClass: "fa-brands fa-twitter",
    taskDescription: "Follow the Twitter channel",
    reward: "500",
    taskType: "joinCommunity",
    taskLink: "https://twitter.com",
    verification: "unverified",
    category: "DAILY TASKS",
  },
  {
    platform: "YouTube",
    iconClass: "fa-brands fa-youtube",
    taskDescription: "watch YouTube video for code",
    reward: "500",
    videoCode: "503210",
    taskType: "watchVideo",
    taskLink: "https://www.youtube.com",
    verification: "unverified",
    category: "DAILY TASKS",
  },
  {
    platform: "TikTok",
    iconClass: "fa-brands fa-tiktok",
    taskDescription: "Follow the TikTok channel",
    reward: "500",
    taskType: "joinCommunity",
    taskLink: "https://www.tiktok.com",
    verification: "unverified",
    category: "DAILY TASKS",
  },
  {
    platform: "Telegram",
    iconClass: "fa-brands fa-telegram",
    taskDescription: "Follow the TG channel",
    reward: "500",
    groupChatId: "testhroup21",
    taskType: "joinTelegramCommunity",
    taskLink: "https://t.me/testhroup21",
    verification: "unverified",
    category: "DAILY TASKS",
  },
  {
    platform: "Twitter",
    iconClass: "fa-brands fa-twitter",
    taskDescription: "Follow the Twitter channel",
    reward: "500",
    taskType: "joinCommunity",
    taskLink: "https://twitter.com",
    verification: "unverified",
    category: "DAILY TASKS",
  },
  {
    platform: "YouTube",
    iconClass: "fa-brands fa-youtube",
    taskDescription: "Follow the YouTube channel",
    reward: "500",
    taskType: "joinCommunity",
    taskLink: "https://www.youtube.com",
    verification: "unverified",
    category: "DAILY TASKS",
  },
  {
    platform: "TikTok",
    iconClass: "fa-brands fa-tiktok",
    taskDescription: "Follow the TikTok channel",
    reward: "500",
    taskType: "joinCommunity",
    taskLink: "https://www.tiktok.com",
    verification: "unverified",
    category: "DAILY TASKS",
  },
  {
    platform: "Telegram",
    iconClass: "fa-brands fa-telegram",
    taskDescription: "Follow the TG channel",
    reward: "500",
    groupChatId: "testhroup21",
    taskType: "joinTelegramCommunity",
    taskLink: "https://t.me/testhroup21",
    verification: "unverified",
    category: "DAILY TASKS",
  },
  {
    platform: "Twitter",
    iconClass: "fa-brands fa-twitter",
    taskDescription: "Follow the Twitter channel",
    reward: "500",
    taskType: "joinCommunity",
    taskLink: "https://twitter.com",
    verification: "unverified",
    category: "DAILY TASKS",
  },
  {
    platform: "YouTube",
    iconClass: "fa-brands fa-youtube",
    taskDescription: "Watch YouTube channel for profit per hour",
    reward: "1000",
    videoCode: "503210",
    taskType: "profitPerHour",
    taskLink: "https://www.youtube.com",
    verification: "unverified",
    category: "PROFIT TASKS",
  },
  {
    platform: "Ton",
    iconClass: "tonicon-svg",
    taskDescription: "make a ton transaction 0.2Ton",
    reward: "5000",
    taskType: "tonTransaction",
    taskLink: "https://www.tiktok.com",
    verification: "unverified",
    category: "AIRDROP TASKS",
  },
  {
    platform: "Telegram",
    iconClass: "fa-brands fa-telegram",
    taskDescription: "Follow the TG channel",
    reward: "500",
    groupChatId: "testhroup21",
    taskType: "joinTelegramCommunity",
    taskLink: "https://t.me/testhroup21",
    verification: "unverified",
    category: "DAILY TASKS",
  },
  {
    platform: "Twitter",
    iconClass: "fa-brands fa-twitter",
    taskDescription: "Follow the Twitter channel",
    reward: "500",
    taskType: "joinCommunity",
    taskLink: "https://twitter.com",
    verification: "unverified",
    category: "DAILY TASKS",
  },
  {
    platform: "friends",
    iconClass: "fa-solid fa-user-group",
    taskDescription: "Refer 3 friends",
    friendsCount: "3",
    reward: "3000",
    taskType: "profitPerHour",
    taskLink: "https://t.me/Tom_Cat_Affiliate_bot",
    verification: "unverified",
    category: "AIRDROP TASKS",
  },
  // {
  //   platform: "emoji",
  //   iconClass: "tomcaticon-svg",
  //   taskDescription: "copy emoji and add to your profile username",
  //   // friendsCount: "3",
  //   reward: "1000",
  //   taskType: "profitPerHour",
  //   taskLink: "https://t.me/Tom_Cat_Affiliate_bot",
  //   verification: "unverified",
  //   category: "AIRDROP TASKS",
  // },
];

module.exports = tasksJson;
